# Hardcode your Aiven MySQL credentials here
spring.datasource.url=jdbc:mysql://mysql-c44e5b6-fanogaajanelle-59ac.d.aivencloud.com:14501/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_pAJW6DfISiqRww3Pp92
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8081
